### PR TITLE
cli: add vclock to vault get/put

### PR DESCRIPTION
**Pull request by dcow**
TODO:
- [x] fixup vault command
- [x] add api host endpoint to --init/config
- [x] test
- [x] update ssss to v2
- [x] retire api v1

### CODE REVIEW

**Review by ceberly — DISMISSED** [review]
This looks good. Eventually i would like to do some more thorough investigation and testing of whether or not we need all the internal functions that do things on s3 to really be `async` because it makes the code quite a bit harder to read. I think this requires just looking at how whatever http server we land on actually handles requests...

**Comment by dcow** [comment]
The async runtime executor does not spawn a new thread for every async task so you do have to avoid blocking from any async thing. This is the main point of e.g. async_std or tokio's stdlib... to replace any blocking logic with yielding logic.

Also, maybe it's a getting used to it thing but async & `.await` is much more ergonomic to me than `async_std::task::block_on(future)` everywhere.

We could use threads and/or channels if you're not into async/await but until we would decide to do that I wouldn't necessarily try to minimize async.

**Review by ceberly — DISMISSED** [review]

**Comment by dcow** [comment]
@ceberly another thing people do is build two APIs, a sync version and an async version where you swap out the io/blocking calls using config directives so then you can choose how you integrate the library via a cargo feature. This seems a bit overkill for right now but I'd support making sure we structure the code to make this easy in the future so that we can reuse code in both non-async and async contexts to address your concern.

**Review by ceberly — APPROVED** [review]
Approved based on comment in discord

**Review by ceberly — APPROVED** [review]
looks good!

**Pull request merged**
